from os.path import isfile
from random import choices
from string import ascii_letters, digits, punctuation


def keygen() -> str:
    """Generates random key.

    Returns:
        str:
        10 digit random key as a string.
    """
    required_str = ascii_letters + digits + punctuation
    key = "".join(choices(required_str, k=10))
    return key


def check_file(key: str) -> str:
    """Checks the password file to see if the received key is already present. If so re-generates.

    Args:
        key: 10 digit key generated by `keygen()`

    Returns:
        str:
        Returns the received key just to print.
    """
    if isfile('password.txt'):
        with open('password.txt', 'r') as file:
            file = file.read()
        if key not in file:
            with open('password.txt', 'a') as file:
                file.write(f'{key}\n')
        else:
            print('Duplicate password has been generated. Please retry.')
            check_file(key=keygen())
    else:
        with open('password.txt', 'a') as file:
            file.write(f'{key}\n')
    return key


if __name__ == '__main__':
    print(check_file(key=keygen()))
